Assignment/Assignment/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.urlpatterns import format_suffix_patterns
from appThree import views

urlpatterns = [
    path("",include('appThree.urls')),
    path("admin/", admin.site.urls),
    path("userinfo", include('appThree.urls')),
    path("users", include('appThree.urls')),
    path("registration/", include('appThree.urls')),
    path("register/", include('appThree.urls')),
    path("login", include('appThree.urls')),
    path("logout", include('appThree.urls')),
    path("relative/", include('appThree.urls')),
    path("form",include('appThree.urls')),
    # path("form/",views.form_name_view,name='form_name')
]

Assignment/appThree/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from appThree import views

# TEMPLATE TAGGING
app_name = 'appThree'

urlpatterns = [
    path('', views.index, name='index'),
    path('users', views.users, name='USERS'),
    path('userinfo', views.UserInfoList.as_view()),
    path('register/', views.signup, name='register'),
    path('registration/', views.registration, name='registration'),
    path('login', views.user_login, name='login'),
    path('logout', views.user_logout, name='logout'),
    path('relative/', views.relative, name='relative'),
    path('form', views.form_name_view, name='Forms'),
]

Assignment/appThree/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # additional
    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pic',blank=True)

    def __str__(self):
        return self.user.username

class UserInfo(models.Model):
    first_name = models.CharField(max_length=128)
    last_name = models.CharField(max_length=128)
    email = models.EmailField(max_length=264,unique=True)
    

Assignment/appThree/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core import validators
from appThree.models import UserProfileInfo, UserInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta():
        model = User
        fields = ('username', 'email', 'password')
        

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')


class NewUser(forms.ModelForm):
    class Meta():
        model = UserInfo
        fields = '__all__'


# def check_for_z(value):
#     if value[0].lower() != 'z':
#         raise forms.ValidationError("NAME NEEDS TO START WITH Z")
    

# class FormName(forms.Form):
#     name = forms.CharField()
#     email = forms.EmailField()
#     verify_email = forms.EmailField(label='Enter your email again:')
#     text = forms.CharField(widget=forms.Textarea)
#     # botcatcher = forms.CharField(required=False,
#     #                              widget=forms.HiddenInput,
#     #                              validators=[validators.MaxLengthValidator(0)])

#     def clean(self):
#         all_clean_data = super().clean()
#         email = all_clean_data['email']
#         vmail = all_clean_data['verify_email']

#         if email != vmail:
#             raise forms.ValidationError("MAKE SURE EMAILS MATCH!")

    # def clean_botcatcher(self):
    #     botcatcher = self.cleaned_data['botcatcher']
    #     if len(botcatcher) > 0:
    #         raise forms.ValidationError("GOTCHA BOT!")
    #     return botcatcher

Assignment/appThree/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from appThree.models import UserInfo
from . import forms
from appThree.forms import NewUser, UserForm, UserProfileInfoForm

from django.shortcuts import get_object_or_404 
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.urls import reverse

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from . serializers import UserInfoSerializer


# Create your views here.

def index(request):
    return render(request,'appThree/index.html')


@login_required
def special(request):
    return HttpResponse("You are logged in, Nice!")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def signup(request):

    form = NewUser()

    if request.method == "POST":
        form = NewUser(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)
        
        else:
            print('ERROR FORM INVALID')

    return render(request,'appThree/signup.html',{'form':form})

def registration(request):
    
    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid:
            user = user_form.save
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        
        else:
            print(user_form.errors,profile_form.errors)
    
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'appThree/registration.html',
                           {'user_form':user_form,
                            'profile_form':profile_form,
                            'registered':registered})

def users(request):
    user_list = UserInfo.objects.order_by('first_name')
    user_dict = {'users':user_list}
    return render(request,'appThree/users.html',context=user_dict)


def user_login(request):

    if request.method == 'POST':
        user_name = request.POST.get('username')
        passwd = request.POST.get('password')

        user = authenticate(username=user_name, password=passwd)
        
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
            
        else:
            print("Someone Tried to LogIN")
            print("Username: {} and password {}".format(user_name,passwd))
            return HttpResponse("Invalid LogIn details!")
        
    else:
        return render(request,'appThree/login.html',{})
    
class UserInfoList(APIView):

    def get(self, request):
        User1 = UserInfo.objects.all()
        serialize = UserInfoSerializer(User1, many=True)
        return Response(serialize.data)
    
    def post(self):
        pass


def form_name_view(request):
    form = forms.FormName()

    if request.method == 'POST':
        form = forms.FormName(request.POST)

        if form.is_valid():
            print("VALIDATION SUCCESS!")
            print("NAME: "+form.cleaned_data['name'])
            print("EMAIL: "+form.cleaned_data['email'])
            # print("TEXT: "+form.cleaned_data['text'])


    return render(request,'appThree/form_page.html',{'form':form})

def relative(request):
    return render(request,'appThree/relative_url_template.html')

Assignment/templates/appThree/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BASE</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="#">HOME</a></li>
                <li><a class="navbar-link" href="{% url 'appThree:USERS'%}">USERS</a></li>
                <li><a class="navbar-link" href="{% url 'appThree:registration'%}">Register</a></li>
                <li><a class="navbar-link" href="{% url 'admin:index'%}">Admin</a></li>
                
                {% if user.is_authenticated %}
                <li><a class="navbar-link" href="{% url 'appThree:logout'%}">Logout</a></li>

                {% else %}
                <li><a class="navbar-link" href="{% url 'appThree:login'%}">LogIn</a></li>

                {% endif %}


            </ul>
        </div>
    </nav>

    <div class="container">

        {% block body_block %}
        <!-- Anything outside of this will be inherited if extended! -->
        {% endblock %}
    </div>
</body>
</html>

Assignment/templates/appThree/form_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FORMS</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    
    <h1>Fill out the form!</h1>
    <div class="container">
        <form method="POST">

            {{form.as_p}}
            {% csrf_token %}
            
            <input type="submit" class="btn btn-primary" value="SUBMIT">
        </form>        
    </div>
</body>
</html>

Assignment/templates/appThree/index.html
<!DOCTYPE html>
{% extends "appThree/base.html" %}
{% block body_block %}

<div class="jumbotron">
  <h1>WELCOME TO HOME PAGE</h1>
  <h2>Go to /register to Sign UP</h2>
  <h3>Go To /users to check the list of the USERS></form></h3>
</div>

{% endblock %}

Assignment/templates/appThree/login.html
{% extends 'appThree/base.html'%}
{% block body_block %}

<div class="jumbotron">
    <h1>Please Login</h1>
    <form action="{% url 'appThree:login' %}" method="POST">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter Username">

        <label for="password">Password</label>
        <input type="password" name="password">

        <input type="submit" name="" value="Login">

    </form>
{% endblock %}
</div>

Assignment/templates/appThree/registration.html
{% extends 'appThree/base.html' %}
{% load static %}

{% block body_block %}

<div class="jumbotron">
    {% if registered %}
        <h1>Thank You for REGISTERING</h1>
    {% else %}
        <h1>REGISTER Here!</h1>
        <h2>Fill out the Form:</h2>  

        <form enctype="multipart/form-data" method="post">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" name="" value="REGISTER">

        </form>

    {% endif %}

</div>

{% endblock %}

Assignment/templates/appThree/relative_url_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>WELCOME TO RELATIVE URL TEMPLATES</h1>
    <a href="{% url 'appThree:USERS' %}">THE USER PAGE</a>
    <a href="{% url 'admin:index' %}">LINK TO ADMIN</a>
    <a href="{% url 'appThree:index' %}">HOME</a>


</body>
</html>

Assignment/templates/appThree/signup.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Users</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static "css/style.css" %}"/>
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top"></nav>
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'appThree:index'%}">HOME</a></li>
                <li><a class="navbar-link" href="{% url 'appThree:USERS'%}">USERS</a></li>
                <li><a class="navbar-link" href="{% url 'appThree:register'%}">Register</a></li>
                <li><a class="navbar-link" href="{% url 'admin:index'%}">Admin</a></li>
                
            </ul>
        </div>
    <h1> Please Sign Up Here!</h1>
    <form method="POST">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="SUBMIT">
    </form>

    

</body>
</html>

Assignment/templates/appThree/users.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Users</title>
    <link rel="stylesheet" href="{% static "css/style.css" %}"/>
</head>
<body>
    <div class="container">
        <h1> Please Sign Up Here!</h1>
        <form method="POST">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="SUBMIT">
        </form>

    </div>
        <!-- {% if users %}

    <ol>
        {% for person in users %}
        <li>User Info</li>
            <ul>
                <li>First Name: {{ person.first_name }}</li>
                <li>Last Name: {{ person.last_name }}</li>
                <li>Email: {{ person.email }}</li>
            </ul>
        {% endfor %}
    </ol>

    {% endif %} -->

</body>
</html>